//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTN5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int fId { get; set; }
        public Nullable<int> cId { get; set; }
        public string fText { get; set; }
        public Nullable<decimal> targetMoney { get; set; }
        public Nullable<decimal> accMoney { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string trueName { get; set; }
        public string fPhone { get; set; }
        public string fEmail { get; set; }
        public string fPhoto { get; set; }
        public string fName { get; set; }
    }
}
