//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTN5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int sId { get; set; }
        public int fId { get; set; }
        public Nullable<decimal> sMoney { get; set; }
        public string intro { get; set; }
        public string sName { get; set; }
        public string sPhoto { get; set; }
    }
}
