//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTN5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int sponsorId { get; set; }
        public Nullable<int> sId { get; set; }
        public Nullable<int> fId { get; set; }
        public string payMethod { get; set; }
        public string location { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string recipient { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> uId { get; set; }
    }
}
